name=DFRobot_EG800AK
version=1.0.0
author=DFRobot
maintainer=PLELES<feng.yang@dfrobot.com>
sentence=Library for DFRobot EG800AK 4G module.
paragraph=The EG800AK is a 4G module for IoT applications.
category=Communication
url=https://github.com/DFRobot/DFRobot_EG800AK
architectures=*
